default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: dev1
  username: jameslordenderlaing

test:
  <<: *default
  encoding: unicode
  database: test1
  username: jameslordenderlaing

production:
  <<: *default